#+title: YAMS: Yet Another Media Server

This is a highly opinionated media server.

* Description
:PROPERTIES:
:ID:       280135a0-2cff-4e93-8679-7d1a6d56b7b2
:END:
This script installs the following software:
- [[https://sonarr.tv/][Sonarr]]
- [[https://radarr.video/][Radarr]]
- [[https://emby.media/][Emby]]
- [[https://www.qbittorrent.org/][qBittorrent]]
- [[https://www.bazarr.media/][Bazarr]]
- [[https://github.com/Jackett/Jackett][Jackett]]

With this combination, you can create a fully functional media server that is going to download,
categorize, subtitle and serve your favorite shows and movies.

* Features
:PROPERTIES:
:ID:       0e072c32-3158-4961-869c-49920090f3d5
:END:
In no particular order:
- *Automatic shows/movies download*: Just add your shows and movies to the watch list and it should
  automatically download the files when they are available.
- *Automatic clasification and organization*: Your media files should be completely organized by default.
- *Automatic subtitles download*: Self explanatory. Your media server should automatically download
  subtitles in the languages you choose, if they are available.
- *Support for Web, Android, iOS, Android TV and whatever that can support Emby*: Since we are
  leveraging from Emby, you should be able to watch your favorite media almost anywhere.

* Dependencies
:PROPERTIES:
:ID:       01577a0a-852e-481a-b9b3-791b68594f96
:END:
First, you need to install:
- [[https://www.docker.com/][docker]]
- [[https://docs.docker.com/compose/][docker-compose]]

* Before running
:PROPERTIES:
:ID:       1c609bfc-4e6e-4fd8-8129-1b722fd7cda8
:END:
Before installing, make sure you have:
- *An installation location*: The script is going to ask you for a install location, but it will default
  to ~/opt/yams~. Just make sure your current user has permissions to write on the selected directory.
- *A media folder*: This is the folder where all your files are going to be downloaded and categorized. If
  you choose ~/srv/media~, the script is going to create the following folders:
  + ~/srv/media/tv~: For your TV shows
  + ~/srv/media/movies~: For your movies
  + ~/srv/media/downloads~: For your torrent downloads
  + ~/srv/media/blackhole~: For your torrents blackhole
- *A regular user to run and own the media files*: You shouldn't use ~root~ for this user, but I'm not
  your father, nothing is going to stop you lol

* To run
:PROPERTIES:
:ID:       a0417c61-3fd8-40a0-9385-6c5aaed37337
:END:

#+begin_src bash
$ git clone https://gitlab.com/rogs/yams.git
$ cd yams
$ ./install.sh
#+end_src

And follow the instructions.


So far, I've tested this in Debian 11, but it should work on Ubuntu as well.

* Usage
:PROPERTIES:
:ID:       9e995141-b386-4962-9842-7209bedc5651
:END:
When the script finishes installing without issues, just run:
#+begin_src
$ yams
yams - Yet Another Media Server

Usage: yams [--help|restart|stop|start|status]
options:
--help     displays this help message
restart    restarts yams services
stop       stops all yams services
start      starts yams services
destroy    destroy yams services so you can start from scratch
#+end_src

* Donations
:PROPERTIES:
:ID:       992fb05d-c171-4ba9-9207-3dd1d467656e
:END:
If you *really* wish to donate, first I would like to say thank you from the bottom of my heart! ❤️ Second, I
would prefer you donate to any of the projects used in this script.

They are the ones doing the real work, I just created a docker-compose file and a couple of bash scripts:

- [[https://www.linuxserver.io/donate][linuxserver.io donations page]]
- [[https://sonarr.tv/donate][Sonarr donations page]]
- [[https://radarr.video/donate][Radarr donations page]]
- [[https://emby.media/premiere.html][Emby premier page]] (Recommended! I personally use this service)
- [[https://www.qbittorrent.org/donate][qBittorrent donations page]]
- [[https://www.paypal.com/donate/?cmd=_s-xclick&hosted_button_id=XHHRWXT9YB7WE&source=url][Bazarr donations page]]
- Jackett does not have a donation page 🤔

Just let them know YAMS sent you there 😎

* Special thanks
:PROPERTIES:
:ID:       b0a86edc-dc4f-4ac2-908c-fd08f1d2f99c
:END:
- [[https://info.linuxserver.io/][linuxserver.io]] for their amazing docker images
- [[https://sonarr.tv/][Sonarr]]
- [[https://radarr.video/][Radarr]]
- [[https://emby.media/][Emby]]
- [[https://www.qbittorrent.org/][qBittorrent]]
- [[https://www.bazarr.media/][Bazarr]]
- [[https://github.com/Jackett/Jackett][Jackett]]
- My friends:
  + [[https://github.com/xploshioOn][xploshioOn]]
  + [[https://github.com/norlis][norlis]]
  + [[https://github.com/isaac152][isaac152]]
  For giving me ideas and helping me test the script
- You 🫵, for being such an amazing human being, checking out my repo and (hopefully!) using it on your
  media server. Thank you! 🙇
